workspace(name = "merge_strings_alternately")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# GTest 1.14.0
http_archive(
    name = "com_google_googletest",
    strip_prefix = "googletest-f8d7d77c06936315286eb55f8de22cd23c188571",
    urls = ["https://github.com/google/googletest/archive/f8d7d77c06936315286eb55f8de22cd23c188571.zip"],
)
