add_rules("mode.debug", "mode.release")
set_languages("c++23")
add_requires("gtest 1.15.2", {system = true, configs = {main = true, gmock = true}})
add_requires("gmock 1.15.2", {system = true})

-- Problems
includes("0021_merge_two_sorted_lists")
includes("0098_validate_binary_search_tree")
includes("0102_binary_tree_level_order_traversal")
includes("0121_best_time_to_buy_and_sell_stock")
includes("0142_linked_list_cycle_ii")
includes("0200_number_of_islands")
includes("0205_isomorphic_strings")
includes("0206_reverse_linked_list")
includes("0235_lowest_common_ancestor_bst")
includes("0278_first_bad_version")
includes("0383_ransom_note")
includes("0392_is_subsequence")
includes("0409_longest_palindrome")
includes("0412_fizzbuzz")
includes("0589_nary_tree_preorder_traversal")
includes("0704_binary_search")
includes("0724_find_pivot_index")
includes("0733_flood_fill")
includes("0876_mid_linked_list")
includes("1342_number_of_steps_to_reduce_to_zero")
includes("1480_running_sum")
includes("1672_richest_customer_wealth")
includes("1768_merge_strings_alternately")

-- Data structures tutorial
includes("tut_max_avg_subarray_1")
includes("tut_reverse_string_in_place")
includes("tut_squares_of_sorted_array")
