FROM fedora:43
RUN dnf install -y which
RUN dnf install -y plocate
RUN dnf install -y awk
RUN dnf install -y git
RUN dnf install -y cmake-3.31.6
RUN dnf install -y xmake-3.0.0
RUN dnf install -y gcc-15.1.1
RUN dnf install -y clang-20.1.7
RUN dnf install -y clang-tools-extra-20.1.7
RUN dnf install -y gtest-devel-1.15.2
RUN dnf install -y gmock-devel-1.15.2
RUN updatedb
